version: "3"
networks:
  wsruler

services:

  cdb:
    build:
      context: .
      dockerfile: Dockerfile_cdb
    expose:
      - "9999"
    networks:
      - wsruler

  wsr:
    build:
      context: .
      dockerfile: Dockerfile_wsr
    expose:
      - "9999"
    networks:
      - wsruler
    depends_on:
      - cdb

